### ISSUE TITLE
"view comments" links don't appear when expected

### ISSUE THREAD

**Issue by lsloan** [longhornopen/canvas-peer-grade-calculator#12]
When viewing the reviews for an assignment, the right column of "View Comments" links is not shown at first.  Activating the "Show Comments" button adds the right column with those links.  It appears to be good.

However, navigating to the next page of reviews shows an empty column.  There are no links.  Not even borders between rows are shown in the column.

Activating the "Hide Comments" button followed by the "Show Comments" button again will fix the current page.  Navigating back to the previous page shows it still has a column of "View Comments" links.  Navigating to any other page besides those two shows a blank column again.  To make the links appear for each page of reviews, the user needs to activate the "Hide Comments" button followed by the "Show Comments" button each time.

**Comment by lsloan** [comment]
@chrispittman, some UMich people have reviewed your peer grade tool for use as a general peer review assignment tool.  That is, they don't use peer grading, but they would like to use this tool as a possibly quicker or more convenient way to access information about peer reviewed assignments than the tools Canvas offers.

I've been asked to open issues in this repo to report some problems and maybe ask about additional features.  This is the first of a few issues.

**Comment by chrispittman** [comment]
Should be fixed now.

**Comment by lsloan** [comment]
I'm trying to use release `ghcr.io/longhornopen/canvaspeergrade:20230418` and I still see the problem.  I believe I've set it up correctly.  You can see my `Dockerfile` in my fork branch at: https://github.com/lsloan/docker-base-images/blob/cf894c3b3230a225efeb2d831101ebc6e78ba5ec/canvas-peer-grade-calculator/Dockerfile.umich

I launch the app for local testing with `docker compose up`.  I use https://loophole.cloud/ to route requests to the app running on my local machine.  The `README.md` in the same directory as the `Dockerfile` goes into more detail.

**Comment by chrispittman** [comment]
This bug was fixed two weeks ago; the `20230418` build you're referencing doesn't contain the fix.  Try the new `20230525` build instead.
